### ISSUE TITLE
Quelques commentaires

### ISSUE THREAD

**Issue by Torf** [madbrain/goldrush-simu#1]
Salut ludo,

Ça tourne pas mal pour le moment mais j'ai deux trois questions : 
- ça va être chaud d'avoir des bases équilibrées, c'est prévu des rounds avec échanges de bases ? J'ai remarqué sur la carte de test de très grandes disparités.
- Des fois le serveur dit qu'une case est un diamant alors qu'elle est à 0 (et l'affiche sur l'interface) mais une fois qu'on PICK dessus elle disparaît. Est-ce bien normal ? (Je viens de voir que c'est apparemment la carte qui contient des 0, il serait bien que le serveur le convertisse en Mud d'après moi)
- Actuellement, on ne sais pas où sont les bases ennemies. J'avais cru entendre qu'on devait les voir (pas de brouillard sur les bases).
- J'ai remarqué que tu as prévu une interface "PlayerConnection", une autre méthode de connexion pourrait être possible ? (je pense aux sockets TCP). L'actuelle solution n'est pas très pratique au niveau du débogage, vu que l'application qu'on développe est lancée par le serveur et non par notre IDE.
- Le nombre officiel de round est quand à lui de 1000 ? Si celui-ci peut changer, il serait  peut-être intéressant de le recevoir avec les informations de la carte.
- Imho, il serait bien que le serveur kill les process qu'il a lancé à la fin de la partie. Vu que dans nos programme on connaît pas la fin ( while(true) ...) , ça fait des processus qui traînent après. :P

Voila, j'avais envie de faire chier le monde avec mes remarques :P 

Bon weekend et bonnes fêtes ;)

edit: ajout du dernier point. Suppression du point sur time limit ( j'avais pas compris le fonctionnement de -t )

**Comment by madbrain** [comment]
1 - La carte proposée à été générée aléatoirement et ensuite ajustée manuellement pour que tous les diamants soient accessibles, c'est vraiment pas idéale, je compte donc sur les participants pour proposer des cartes plus intéressantes et équilibrées. Le format des combats sera sûrement sous la forme d'un championnat avec plusieurs match sur le même terrain, par exemple, deux mi-temps comme au foot et on inverse les bases.

2 - Bonne remarque, la carte utilise un ancien encodage où 0 sur la carte vaut 1, 1 vaut 2, etc. il faut donc incrémenter de 1 tous les diamants de la carte. Il faudrait effectivement que je rajoute la conversion à la lecture de la carte.

3 - Il faut plusieurs joueurs pour voir les autres bases, elle est marquée d'un 'X' comme sa propre base.

4 - non, c'est pas prévu directement dans le simulateur, mais il est tout à fait possible de développer un petit bouchon qui fait la conversion entre entrée/sortie standards et TCP et qui sera lancé par le simulateur.

5 - C'est possible, c'est à discuter sur le forum.

6 - il est vrai que la fin de jeu n'est pas vraiment prévue... En théorie à la fermeture du simulateur les entrée/sortie de chaque joueur sont fermées et déclenche donc un exception à la lecture ce qui peut être détecté par le joueur et terminer proprement le processus. Je vais voir s'il y a moyen de faire un terminaison plus propre.

Merci pour toutes ces remarques !
